import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-fixed": "#0d1c2d",
        "primary-fixed-dim": "#adc6ff",
        "on-background": "#dae2fd",
        "surface-variant": "#2d3449",
        "on-secondary-container": "#00515d",
        "surface-dim": "#0b1326",
        "surface-container-highest": "#2d3449",
        "on-primary": "#002e6a",
        "on-tertiary": "#233143",
        "on-error": "#690005",
        "surface-container-lowest": "#060e20",
        "surface-bright": "#31394d",
        "inverse-primary": "#005ac2",
        "secondary-fixed-dim": "#2fd9f4",
        "on-secondary-fixed": "#001f25",
        "on-primary-fixed": "#001a42",
        "on-surface": "#dae2fd",
        "on-tertiary-container": "#1c2b3c",
        "surface-tint": "#adc6ff",
        "on-error-container": "#ffdad6",
        "surface-container": "#171f33",
        "tertiary-fixed-dim": "#b9c8de",
        "on-secondary-fixed-variant": "#004e5a",
        primary: "#adc6ff",
        "secondary-container": "#00cbe6",
        "tertiary-fixed": "#d4e4fa",
        "primary-container": "#4d8eff",
        "error-container": "#93000a",
        "surface-container-low": "#131b2e",
        "tertiary-container": "#8392a6",
        "on-secondary": "#00363e",
        tertiary: "#b9c8de",
        "on-tertiary-fixed-variant": "#39485a",
        "on-primary-container": "#00285d",
        secondary: "#5de6ff",
        surface: "#0b1326",
        "primary-fixed": "#d8e2ff",
        "inverse-surface": "#dae2fd",
        "outline-variant": "#424754",
        "secondary-fixed": "#a2eeff",
        "inverse-on-surface": "#283044",
        "on-surface-variant": "#c2c6d6",
        outline: "#8c909f",
        "surface-container-high": "#222a3d",
        error: "#ffb4ab",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1440px",
        "stack-xl": "80px",
        "stack-lg": "48px",
        "section-gap": "120px",
        gutter: "32px",
        "margin-mobile": "20px",
        "stack-md": "24px",
        "stack-sm": "12px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "display-lg-mobile": ["var(--font-jetbrains-mono)", "monospace"],
        "code-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-jetbrains-mono)", "monospace"],
        "display-lg": ["var(--font-jetbrains-mono)", "monospace"],
        "label-caps": ["var(--font-jetbrains-mono)", "monospace"],
        sans: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: {
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "label-caps": [
          "11px",
          { lineHeight: "1.0", letterSpacing: "0.2em", fontWeight: "600" },
        ],
        "display-lg": [
          "64px",
          { lineHeight: "1.05", letterSpacing: "-0.05em", fontWeight: "800" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "300" }],
      },
    },
  },
  plugins: [],
};

export default config;
